### ISSUE TITLE
Guia de instalação e utilização

### ISSUE THREAD

**Issue by jcserracampos** [labhackercd/audiencias-publicas#2]
Olá,
Acredito que falta um README.md sobre como utilizar.

Sou da Alego e estou querendo contribuir com o projeto e talvez utilizar no nosso legislativo.

**Comment by erivanio** [comment]
Bom dia @jcserracampos, desculpa a demora. Agora estamos disponibilizando toda a plataforma e-Democracia em conjunto com o Interlegis do Senado para as casas legislativas. Você pode saber mais através do [edemocracia.leg.br](http://www.edemocracia.leg.br/) .
