### ISSUE TITLE
Partidos escondidos ou camuflados

### ISSUE THREAD

**Issue by eduamf** [labhackercd/audiencias-publicas#66]
Apesar de insistir na necessidade de que estejam disponíveis o número da legenda nas votações eletrônicas, ou não , nas orientações de liderança e nas votações simbólicas, percebo que isto ainda não é um fato, sendo ainda necessário muito ajuste para que os partidos não fiquem camuflados pelos blocos parlamentares (ou políticos), ou até mesmo pelo mudança de nomes. 

Todo partido político tem o número da legenda junto ao TSE e isso permite que se rastreie os mesmos. Nas votações anteriores a novembro de 2017 não estão disponíveis os números dos partidos para consulta a qualquer momento.

Outro ponto é a necessidade de que as votações simbólicas com orientação de liderança sejam gravadas efetivamente, o que já seria possível desde o final de 2016. As votações simbólicas apresentadas no painel por terem orientação devem ter seus registros mantidos para consulta posterior.

**Comment by erivanio** [comment]
Bom dia @eduamf , encaminhe as solicitações para dadosabertos.ditec@camara.leg.br. A solicitação pode ser feita também pela página de dados abertos da Câmara (https://dadosabertos.camara.leg.br).
